spring:
  cloud:
    gateway:
      routes:
        # Ruta para registro de eventos (nueva)
        - id: event-registration
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/registration
            - Method=POST

        # Ruta existente para obtener asistentes (se mantiene igual)
        - id: event-attendees
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/registration/attendees/*
          # Ruta para GET /api/events (obtener todos los eventos)
        - id: events-get-all
          uri: ${EVENT_SERVICE} # MS de Eventos
          predicates:
            - Path=/api/events
            - Method=GET

        # Ruta para GET /api/events/{id} (obtener un evento específico)
        - id: events-get-by-id
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/{id}
            - Method=GET

        # Ruta para POST /api/events (crear evento)
        - id: events-create
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events
            - Method=POST

        # Ruta para PUT /api/events/{id} (actualizar evento)
        - id: events-update
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/{id}
            - Method=PUT

        # RUTAS DE MS PROFILE
        - id: auth-login
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/login
            - Method=POST

        # Perfil de usuario
        - id: user-profile
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/profile
            - Method=GET

        # Registro de usuario
        - id: user-register
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/registerUser
            - Method=POST

        # Consultas de usuarios (GraphQL)
        - id: users-find-by-ids
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/findUsersByIds
            - Method=POST

        - id: users-find-all
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/findAll
            - Method=GET

        - id: user-find-by-id
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/findById
            - Method=GET


        # Operaciones CRUD
        - id: user-update
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/updateUser
            - Method=PUT

        - id: user-remove
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/removeUser
            - Method=DELETE

