server:
  port: 7080
#  ssl:
#    enabled: true
#    key-store: classpath:ssl/keystore.p12
#    key-store-password: NuevaClaveSegura123
#    key-store-type: PKCS12
#    key-alias: andariegos

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - ${CLIENT_SERVICE}
              - http://localhost:3000
              - https://localhost:3000
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        # ruta de reportes
        - id: all-report-route
          uri: ${REPORTS_SERVICE}
          predicates:
            - Path=/api/report
            - Method=GET

        - id: report-by-id-route
          uri: ${REPORTS_SERVICE}
          predicates:
            - Path=/api/report/{id}
            - Method=GET

        - id: report-by-state-route
          uri: ${REPORTS_SERVICE}
          predicates:
            - Path=/api/report/state/{state}
            - Method=GET

        - id: delete-report
          uri: ${REPORTS_SERVICE}
          predicates:
            - Path=/api/report/{id}
            - Method=DELETE
          filters:
            - RewritePath=/api/report/(?<id>.*), /api/reports/$\{id}
        
        - id: update-report
          uri: ${REPORTS_SERVICE}
          predicates:
            - Path=/api/report/{id}
            - Method=PUT
          filters:
            - RewritePath=/api/report/(?<id>.*), /api/reports/$\{id}

        - id: post-report
          uri: ${REPORTS_SERVICE}
          predicates:
            - Path=/api/report
            - Method=POST
          filters:
            - RewritePath=/api/report, /api/reports/

        # Ruta para registro de eventos (nueva)
        - id: event-registration
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/registration
            - Method=POST

        # Ruta existente para obtener asistentes (se mantiene igual)
        - id: event-attendees
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/registration/attendees/*
          
        # Ruta para GET /api/events (obtener todos los eventos)
        - id: events-get-all
          uri: ${EVENT_SERVICE} # MS de Eventos
          predicates:
            - Path=/api/events
            - Method=GET

        # Ruta para GET /api/events/{id} (obtener un evento específico)
        - id: events-get-by-id
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/{id}
            - Method=GET

        # Ruta para POST /api/events (crear evento)
        - id: events-create
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events
            - Method=POST
        
        # Ruta para DELETE /api/events/{id} (eliminar evento)
        - id: events-delete
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/{id}
            - Method=DELETE

        # Ruta para PUT /api/events/{id} (actualizar evento)
        - id: events-update
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/events/{id}
            - Method=PUT

        # Ahora con tours
        - id: tours-create
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/tours
            - Method=POST

        - id: tours-update
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/tours/{id}
            - Method=PUT
          
        - id: tours-delete
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/tours/{id}
            - Method=DELETE
        
        - id: tours-get-by-id
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/tours/{id}
            - Method=GET

        - id: tours-get-all
          uri: ${EVENT_SERVICE}
          predicates:
            - Path=/api/tours
            - Method=GET

        # RUTAS DE MS PROFILE
        - id: auth-login
          uri: ${AUTH_SERVICE}
          predicates:
            - Path=/api/auth/login
            - Method=POST

        - id: auth-register
          uri: ${AUTH_SERVICE}
          predicates:
            - Path=/api/auth/register
            - Method=POST

        # Perfil de usuario
        - id: user-profile
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/profile
            - Method=GET
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        # Registro de usuario
        - id: user-register
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/registerUser
            - Method=POST
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        # Consultas de usuarios (GraphQL)
        - id: users-find-by-ids
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/findUsersByIds
            - Method=POST
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        - id: users-find-all
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/findAll
            - Method=GET
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        - id: user-find-by-id
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/findById
            - Method=GET
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        # Operaciones CRUD
        - id: user-update
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/updateUser
            - Method=PUT
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        - id: user-remove
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/api/removeUser
            - Method=DELETE
          filters:
            - RewritePath=/api/(?<segment>.*), /graphql/api/$\{segment}

        - id: graphql
          uri: ${PROFILE_SERVICE}
          predicates:
            - Path=/graphql/**
          filters:
            - RewritePath=/graphql/(?<segment>.*), /${segment}